version: '3.8'

services:
  macreplay:
    build: .
    container_name: macreplay
    ports:
      - "8059:8059"
    volumes:
      # Persist configuration and logs
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - HOST=0.0.0.0:8059
      - CONFIG=/app/data/MacReplay.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://100.103.131.112:8059/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: if you want to use an external network
# networks:
#   default:
#     external: true
#     name: your-network-name 